app_group:
  - read:
      path: /apps/appstore.eda.nokia.com
      method: GET

intent_targets:
  - read:
      path: /apps/appstore.eda.nokia.com/v1/catalogs/{name}/_targets
      method: GET
  - read:
      path: /apps/appstore.eda.nokia.com/v1/registries/{name}/_targets
      method: GET

k8_s_topology_request:
  - create:
      path: /apps/appstore.eda.nokia.com/v1/catalogs/{name}/_topology
      method: POST
  - create:
      path: /apps/appstore.eda.nokia.com/v1/registries/{name}/_topology
      method: POST

resource_history:
  - read:
      path: /apps/appstore.eda.nokia.com/v1/catalogs/{name}/_revs
      method: GET
  - read:
      path: /apps/appstore.eda.nokia.com/v1/registries/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/appstore.eda.nokia.com/v1
      method: GET

resource_topology:
  - read:
      path: /apps/appstore.eda.nokia.com/v1/catalogs/{name}/_topology
      method: GET
  - read:
      path: /apps/appstore.eda.nokia.com/v1/registries/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/appstore.eda.nokia.com/v1/catalogs/{name}
      method: DELETE
  - delete:
      path: /apps/appstore.eda.nokia.com/v1/registries/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/appstore.eda.nokia.com/v1/_ui/{pathname}
      method: GET

workflow_get_inputs_resp_elem:
  - read:
      path: /workflows/v1/appstore.eda.nokia.com/v1/appinstallers/{name}/_input
      method: GET

workflow_input_data:
  - update:
      path: /workflows/v1/appstore.eda.nokia.com/v1/appinstallers/{name}/_input
      method: PUT

com.nokia.eda.appstore.v1.app_installer:
  - create:
      path: /workflows/v1/appstore.eda.nokia.com/v1/appinstallers
      method: POST
  - read:
      path: /workflows/v1/appstore.eda.nokia.com/v1/appinstallers/{name}
      method: GET

com.nokia.eda.appstore.v1.app_installer_list:
  - read:
      path: /workflows/v1/appstore.eda.nokia.com/v1/appinstallers
      method: GET

com.nokia.eda.appstore.v1.catalog:
  - create:
      path: /apps/appstore.eda.nokia.com/v1/catalogs
      method: POST
  - read:
      path: /apps/appstore.eda.nokia.com/v1/catalogs/{name}
      method: GET
  - update:
      path: /apps/appstore.eda.nokia.com/v1/catalogs/{name}
      method: PUT
  - update:
      path: /apps/appstore.eda.nokia.com/v1/catalogs/{name}
      method: PATCH

com.nokia.eda.appstore.v1.catalog_list:
  - read:
      path: /apps/appstore.eda.nokia.com/v1/catalogs
      method: GET
  - delete:
      path: /apps/appstore.eda.nokia.com/v1/catalogs
      method: DELETE

com.nokia.eda.appstore.v1.catalog_deleted_resources:
  - read:
      path: /apps/appstore.eda.nokia.com/v1/catalogs/_deleted
      method: GET

com.nokia.eda.appstore.v1.registry:
  - create:
      path: /apps/appstore.eda.nokia.com/v1/registries
      method: POST
  - read:
      path: /apps/appstore.eda.nokia.com/v1/registries/{name}
      method: GET
  - update:
      path: /apps/appstore.eda.nokia.com/v1/registries/{name}
      method: PUT
  - update:
      path: /apps/appstore.eda.nokia.com/v1/registries/{name}
      method: PATCH

com.nokia.eda.appstore.v1.registry_list:
  - read:
      path: /apps/appstore.eda.nokia.com/v1/registries
      method: GET
  - delete:
      path: /apps/appstore.eda.nokia.com/v1/registries
      method: DELETE

com.nokia.eda.appstore.v1.registry_deleted_resources:
  - read:
      path: /apps/appstore.eda.nokia.com/v1/registries/_deleted
      method: GET

totalPaths: 22
totalSchemas: 70
usedSchemas: 18
unusedSchemas: 52
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - IntentTarget
  - K8SPatchOp
  - OverlayState
  - Patch
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoAttribute
  - TopoBoolExpression
  - TopoBoolLiteral
  - TopoElemMetadata
  - TopoEndpointBoolExpression
  - TopoField
  - TopoFixedBoolExpression
  - TopoLabelSelector
  - TopoLiteralStatusOrBadge
  - TopoLiteralValue
  - TopoLogicalExpression
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkGroup
  - TopoOverlayLinkGroupEndpoint
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeOrGroup
  - TopoOverlayNodeState
  - TopoOverlayValue
  - TopoSchema
  - TopoStateFilter
  - TopoValue
  - TopoValueExpression
  - Topology
  - WorkflowIdentifier
  - WorkflowInputDataElem
  - com.nokia.eda.appstore.v1.AppInstaller_alarms
  - com.nokia.eda.appstore.v1.AppInstaller_deviations
  - com.nokia.eda.appstore.v1.AppInstaller_metadata
  - com.nokia.eda.appstore.v1.Catalog_DeletedResourceEntry
  - com.nokia.eda.appstore.v1.Catalog_alarms
  - com.nokia.eda.appstore.v1.Catalog_deviations
  - com.nokia.eda.appstore.v1.Catalog_metadata
  - com.nokia.eda.appstore.v1.Registry_DeletedResourceEntry
  - com.nokia.eda.appstore.v1.Registry_alarms
  - com.nokia.eda.appstore.v1.Registry_deviations
  - com.nokia.eda.appstore.v1.Registry_metadata
